---
output:
  github_document:
    pandoc_args: --webtex
always_allow_html: true
bibliography: Paper/references.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Active travel-based accessibility: A review of data sources and needs from a Canadian perspective

<!-- badges: start -->
<!-- badges: end -->

Mahdis Moghadasi (School of Earth, Environment and Society, McMaster University)  
Jeneva Beairsto (Faculty of Health Sciences, Simon Fraser University)  
Meghan Winters (Faculty of Health Sciences, Simon Fraser University)  
Antonio Paez (School of Earth, Environment and Society, McMaster University) 

## Abstract

Active travel is a key element to achieve robust and healthy urban transportation polycultures. As analysis of transportation needs in cities shifts from a focus on mobility to accessibility, the need to assess accessibility by cycling and walking has become incresingly pressing. The distinguishing features of these modes – lower speeds, shorter trips, potentially different purposes compared to motorized trips – means that the data inputs required for accessibility analysis are not necessarily the same as those used for the study of accessibility for motorized travel. The objective of this review is to assess the sources of data and data needs to implement active accessibility analysis. Walking-specific and cycling-specific geographic accessibility measures and data applied within recently published literature are reviewed. Walking and cycling accessibility measures are compared in terms of the types of metrics, the origins and destinations considered, geographic scales, and travel time or distance calculations. In comparing approaches for walking versus cycling, this report also highlights possible considerations, challenges, and questions that emerge when considering the future of active travel accessibility-based analysis.  The discussion in this review is centered on the Canadian context but the lessons may be more broadly applicable to other national contexts.

## Introduction

Active travel is a key component of efforts in urban areas as they try to achieve more robust and healthy urban transportation polycultures [@lavery2013; @millera2011; @lira2021]. Cycling and walking are effective modes for short- and mid-range travel in urban areas that have, over a period of decades, grown to accommodate travel by automobile [@brown2009; @wiersma2020] while treating other modes almost as afterthoughts [@brezina2020; @koglin2020; @ruffino2021]. Along with a focus on motorized travel, the focus of transportation planning has been to plan for mobility mainly by car. Transportation and land use systems have been designed to produce mobility, and this is reflected in the use of measures of efficiency that ignore the reason for most travel, which is to reach destinations [@handy1997measuring].

The idea of producing mobility seems intuitive when planning for inexpensive motorized travel, in an era when automobile users have been, as a matter of policy, shielded from paying – and even becoming aware – of the full cost of their travel [@taylor2006]. In recognition of the contradiction of trying to generate mobility while also hoping to reduce the ill effects of mobility, an argument in the transportation literature for decades has been to shift from mobility-based to accessibility-based planning [@handy1997measuring; @unit2003]. Transportation accessibility is commonly defined as the potential of transportation-land use systems to generate access to opportunities [@paez2012] and conceptually strikes at the heart of wasteful mobility-based planning by focusing on the ability to reach destinations. Despite mixed evidence regarding the adoption of accessibility in planning practice [@boisjoly2017; @proffitt2019] there are reasons to believe that the future belongs to accessibility-based planning [@handy2020].

The relevance of accessibility-based planning is even more evident when active modes are considered: who would rather make long trips if equivalent destinations could be reached with shorter trips? Not only can pedestrians and cyclists not be shielded from the cost of travel, the effort of reaching destinations is inherently visceral [@hsu2014; @iseki2014; @paez2020]. As interest in active travel-based accessibility (ATB accessibility) grows globally [@arranz2019; @li2020; @ortega2021evaluating; @rosas2020], transportation scholars have built on decades-worth of accessibility research that mainly focused on motorized travel. In principle, accessibility analysis is sufficiently general to be applicable for ATB accessibility analysis. In practice, it is important to recognize the differences between motorized and active travel, and how they can impact their implementation with a focus on active travel [@iacono2010]. Compared to motorized travel, active travel tends to be slower, happens at smaller scales, is used to reach potentially different destinations, and involves costs, such as physical effort, that are usually are ignored in the analysis of motorized travel.

The objective of the present study is to investigate ATB accessibility with a focus on data sources and needs, using Canada as case study. The research is prompted by a recent Canadian project that has been tasked with developing data-driven standards for the analysis of transportation equity. The need to propose methods that can be used consistently across regions requires a sound understanding of how analysis and outputs can be conditioned by the data inputs. it is important to acknowledge that other reviews of ATB accessibility measures exist [@geurs2004; @iacono2010; @maghelal2011; @talen2013; @vale2016active]. The contribution of this paper is to fill a gap in the literature by focusing on the data required by various measures of ATB accessibility and comparing measures that can be implemented consistently in different contexts, as well as data needs for consistent implementation of the rest.

The reminder of this paper is organized as follows. Section 2 presents a review of methods. Section 3 presents a categorization of the required data according to each of the accessibility measurements. Section 4 provides Important considerations and possible challenges for calculating accessibility by active mode; discussions and conclusions are provided in Section 5.  

## References
