---
title: "Data-Needs-Report"
author: "MM"
format: docx
editor: source
bibliography: references.bib
---

## Abstract

Active travel is a key element to achieve robust and healthy urban transportation polycultures. As analysis of transportation needs in cities shifts from a focus on mobility to accessibility, the need to assess accessibility by cycling and walking has become increasingly pressing. The distinguishing features of these modes --lower speeds, shorter trips, potentially different purposes compared to motorized trips-- means that the data inputs required for accessibility analysis are not necessarily the same as those used for the study of accessibility for motorized travel. The objective of this review is to assess the sources of data and data needs to implement active accessibility analysis. Walking-specific and cycling-specific geographic accessibility measures and data applied within recently published literature are reviewed. Walking and cycling accessibility measures are compared in terms of the types of metrics, the origins and destinations considered, geographic scales, and travel time or distance calculations. In comparing approaches for walking versus cycling, this report also highlights possible considerations, challenges, and questions that emerge when considering the future of active travel accessibility-based analysis.  The discussion in this review is centered on the Canadian context but the lessons may be more broadly applicable to other national contexts.

## Introduction

Active travel is a key component of efforts in urban areas as they try to achieve more robust and healthy urban transportation polycultures [@lavery2013; @millera2011; @lira2021]. Cycling and walking are effective modes for short- and mid-range travel in urban areas that have, over a period of decades, grown to accommodate travel by automobile [@brown2009; @wiersma2020] while treating other modes almost as afterthoughts [@brezina2020; @koglin2020; @ruffino2021]. Along with a focus on motorized travel, the focus of transportation planning has been to plan for mobility mainly by car. Transportation and land use systems have been designed to produce mobility, and this is reflected in the use of measures of efficiency that ignore the reason for most travel, which is to reach destinations [@handy1997measuring].

The idea of producing mobility seems intuitive when planning for inexpensive motorized travel, in an era when automobile users have been, as a matter of policy, shielded from paying --and even becoming aware-- of the full cost of their travel [@taylor2006]. In recognition of the contradiction of trying to generate mobility while also hoping to reduce the ill effects of mobility, an argument in the transportation literature for decades has been to shift from mobility-based to accessibility-based planning [@handy1997measuring; @unit2003]. Transportation accessibility is commonly defined as the potential of transportation-land use systems to generate access to opportunities [@paez2012] and conceptually strikes at the heart of wasteful mobility-based planning by focusing on the ability to reach destinations. Despite mixed evidence regarding the adoption of accessibility in planning practice [@boisjoly2017; @proffitt2019] there are reasons to believe that the future belongs to accessibility-based planning [@handy2020].

The relevance of accessibility-based planning is even more evident when active modes are considered: who would rather make long trips if equivalent destinations could be reached with shorter trips? Not only can pedestrians and cyclists not be shielded from the cost of travel, the effort of reaching destinations is inherently visceral [@hsu2014; @iseki2014; @paez2020]. As interest in active travel-based accessibility (ATB accessibility) grows globally [@arranz2019; @li2020; @ortega2021evaluating; @rosas2020], transportation scholars have built on decades-worth of accessibility research that mainly focused on motorized travel. In principle, accessibility analysis is sufficiently general to be applicable for ATB accessibility analysis. In practice, it is important to recognize the differences between motorized and active travel, and how they can impact their implementation with a focus on active travel [@iacono2010]. Active modes of transportation absorbed the interest of researchers because they have significant implications and combines unrivalled advantages such as environment, health, and social inclusion [@pucher2010walking;@rojas2011health; @rojas2012replacing;@otero2018health;@koszowski2019active; @tinessa2021walkability]. They have been linked to a variety of health benefits. For example, they improve longevity [ @hakim1998effects], cognitive function [ @weuve2004physical], quality of life [@strawbridge1996successful;@leveille1999aging], and are perceived as cleaner and more efficient sustainable modes of transportation [@bhopal1995cycling]. They also become an excellent alternative for decarbonizing mobility, lowering transportation costs for families, promoting gender equality, building resilient structures, and contributing to the aesthetic value of the environment [@koszowski2019active]. They also improve accessibility for those who do not have other modes of transportation and aid in the development of local and regional economies. However, compared to motorized travel, active travel is slower, occurs on smaller scales, has less safety due to their higher risk of being severely injured in collisions than motorized vehicle drivers, is used to reach potentially different destinations, and involves costs, such as physical effort, that are typically ignored in motorized travel analysis [@ng2017cyclist;@akgun2018cyclist; @pokorny2018conflicts; @oehl2019cyclists; @useche2019healthy].

The objective of the present study is to investigate ATB accessibility with a focus on data sources and needs, using Canada as case study. The research is prompted by a recent Canadian project that has been tasked with developing data-driven standards for the analysis of transportation equity. The need to propose methods that can be used consistently across regions requires a sound understanding of how analysis and outputs can be conditioned by the data inputs. it is important to acknowledge that other reviews of ATB accessibility measures exist [@geurs2004; @iacono2010; @maghelal2011; @talen2013; @vale2016active]. The contribution of this paper is to fill a gap in the literature by focusing on the data required by various measures of ATB accessibility and comparing measures that can be implemented consistently in different contexts, as well as data needs for consistent implementation of the rest.

The reminder of this paper is organized as follows. Section 2 presents a review of methods. Section 3 presents a categorization of the required data according to each of the accessibility measurements. Section 4 provides Important considerations and possible challenges for calculating accessibility by active mode; discussions and conclusions are provided in Section 5.  


## Background 

The concept of accessibility has long been adopted in both spatial and transportation research to assess the quality and extent of the relationships between spatial development of a certain area and the transportation system serving it. The seminal work of Hansen (1959) defined accessibility as "the potential of opportunities for interaction", measuring the number and variety of opportunities which can be obtained from a specific location by means of the transportation system. In 2004, Geurs and van Wee deconstructed the concept of accessibility into four elements: (i) land use, which describes the quality, quantity, and spatial distribution of opportunities, such as schools, jobs, hospitals, and recreational facilities as destination places, as well as demand for opportunities at origin places; (ii) transportation, which refers to the transportation system represented by the disutility for a person to travel from an origin to a destination by means of a certain mode of transportation; (iii) time, which accounts for the temporal constraints in terms of the availability of opportunities throughout the day and the available time for people to utilize such kind of opportunities; and iv) individual, which indicates the capabilities (determined by income, education level, travel mode availability, etc.) and needs (determined by age, household situation, etc.) of specific (groups of) persons. The emphasis on different elements of accessibility has resulted in multiple measurement methods and indicators (for example, @geurs2004; Kelobonye et al., 2019; Lee et al., 2010; Neutens, 2015; Paez et al., 2012; and Vandenbulcke et al., 2009), including proximity, cumulative, gravity, utility-based, and space-time prism models as the dominant approaches. However, there are debates about how to measure this concept (Castiglione et al., 2006; Fan et al., 2012; Wang and Chen, 2015).





























$$
A_i = \sum_j^n O_j
$$

| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| 12      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |

: Demonstration of pipe table sytnax {#tbl-example}

As seen in @tbl-example, we can easily do tables in Quarto documents.

## References
